my:
  list: 
    values: one,two,three
  greeting: Hello World from config server spring boot config - microservice specific config file

db:
  connection: "{connectionString: 'http://____', userName: 'foo2', password: 'pass'}"
  host: 127.0.0.1
  port: 1200